[build]
  command   = "npm install --no-audit --no-fund && npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler  = "esbuild"
  included_files = ["data/**"]

[[redirects]]
  from   = "/api/download"
  to     = "/.netlify/functions/download-file"
  status = 200
  force  = true

[[redirects]]
  from   = "/i/:slug"
  to     = "/#/?slug=:slug"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
