[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["octokit", "busboy"]
  included_files = ["data/**"]

[[redirects]]
  from = "/api/download"
  to = "/.netlify/functions/download-file"
  status = 200
  force = true

[[redirects]]
  from = "/i/:slug"
  to = "/#/?investor=:slug"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
