[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]

[[edge_functions]]
  path = "/i/*"
  function = "auth"

[[redirects]]
  from = "/i/*"
  to = "/index.html"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

