[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  # Incluye archivos adicionales si tu app los requiere
  included_files = ["data/**"]

# Endpoints de funciones (antes del fallback de SPA)
[[redirects]]
  from = "/api/download"
  to = "/.netlify/functions/download-file"
  status = 200
  force = true

[[redirects]]
  from = "/i/:slug"
  to = "/#/?investor=:slug"
  status = 200
  force = true

# SPA fallback al final
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
